name: Java CI

on:
  push:
    branches:
      - main
  workflow_dispatch: 

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Проверка кода
      uses: actions/checkout@v2

    - name: Установка JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Сборка с помощью Maven
      run: mvn -B package  

    - name: Запуск тестов
      run: mvn -B test

