name: Java CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout кода
      uses: actions/checkout@v2

    - name: Установка JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'

    - name: Сборка с помощью Maven
      run: mvn -B clean package

    - name: Запуск тестов
      run: mvn -B test
