name: Java CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:  

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout кода
      uses: actions/checkout@v2

    - name: Установка JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Сборка с помощью Maven
      run: mvn -B clean package

    - name: Запуск тестов
      run: mvn -B test

  manual-test: 
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Вывод текущего каталога
        run: pwd
      
      - name: Запуск тестов в ручном режиме
        run: mvn -B test
        env:
          TEST_MODE: manual
